version: '3'
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/boson/mysql/mydir:/mydir
      - ~/boson/mysql/mysql:/var/lib/mysql
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ~/boson/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_USER=devUser"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_DATABASE=boson"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
  mongo:
    image: mongo # 选择mongodb版本
    restart: always  # 自启动
    container_name: mongo
    ports:
      - 27017:27017 # 映射宿主机端口
    volumes:
      - ~/boson/mongo/db:/data/db    # 挂载数据文件，根据实际路径修改 ：前的路径
      - ~/boson/mongo/log:/var/log/mongodb  # 挂载日志文件，根据实际路径修改 ：前的路径
      - ~/boson/mongo/config:/etc/mongo  # 挂载配置文件，根据实际路径修改 ：前的路径

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
#    privileged: true
#    command: redis-server /etc/redis/redis.conf --appendonly yes
#    volumes:
#      - $PWD/data:/data
#      - $PWD/conf/redis.conf:/etc/redis/redis.conf

  neo4j:
    image: neo4j
    container_name: neo4j
    privileged: true
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/123456
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "~/boson/neo4j/data:/var/lib/neo4j/data"
      - "~/boson/neo4j/logs:/var/lib/neo4j/logs"

#  boson:
#    image: cgglyle/boson:dev
#    container_name: boson
#    restart: always
#    ports:
#      - 8080:8080
#    environment:
#      - "LOG_NAME=/var/log/boson"
