spring:
  # 数据源配置
  datasource:
    # 驱动配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boson?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    # 用户名
    username: devUser
    # 密码
    password: 123456
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boson