spring:
  # 数据源配置
  datasource:
    # 驱动配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/boson?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    # 用户名
    username: root
    # 密码
    password: 123456
    hikari:
      max-lifetime: 10000000
      connection-timeout: 5000
      idle-timeout: 3600000
      maximum-pool-size: 12
      minimum-idle: 4
      connection-test-query: SELECT 1

  data:
    mongodb:
      host: mongo
      port: 27017
      database: boson

  redis:
    database: 0
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    connect-timeout: 30000ms