spring:
  # 数据源配置
  datasource:
    # 驱动配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boson?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    # 用户名
    username: root
    # 密码
    password: 123456
    hikari:
      max-lifetime: 10000000
      connection-timeout: 5000
      idle-timeout: 3600000
      maximum-pool-size: 12
      minimum-idle: 4
      connection-test-query: SELECT 1

  data:
    mongodb:
      host: localhost
      port: 27017
      database: boson

  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    connect-timeout: 30000ms

  neo4j:
    authentication:
      username: neo4j
      password: 123456
    uri: bolt://localhost:7687

  flyway:
    # 是否启用flyway
    enabled: true
    #若启动环境中的的数据库中有数据，但是没有flyway的历史表时，
    #false--启动会报错，true--继续生成flyway历史表完成脚本
    baseline-on-migrate: false
    # 执行时标记的tag 默认为<<Flyway Baseline>>
    baseline-description: <<Flyway Baseline>>
    # 脚本位置
    locations: classpath:db/migration
    # 在迁移时，是否校验脚本，假设V1.0__初始.sql已经迁移过了，在下次启动时会校验该脚本是否有变更过，则抛出异常
    validate-on-migrate: true
    # 检测迁移脚本的路径是否存在，如不存在，则抛出异常
    fail-on-missing-locations: true