mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除
      logic-not-delete-value: 0 #逻辑未删除
    banner: false
  mapper-locations: classpath*:mapper/*.xml